# Generated by Django 5.2.5 on 2025-09-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=19),
        ),
    ]
