# Generated by Django 5.2.5 on 2025-09-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_userprofile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='reward',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='solde',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=19),
        ),
    ]
