# Generated by Django 5.2.5 on 2025-09-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_alter_mission_reward_alter_userprofile_solde'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pi_uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
