# Generated by Django 5.2.5 on 2025-09-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_userprofile_pi_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
