# Generated by Django 5.2.5 on 2025-09-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_alter_usersession_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pi_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
