# Generated by Django 5.2.5 on 2025-09-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_alter_userprofile_pi_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Raison du rejet'),
        ),
    ]
