# Generated by Django 5.2.5 on 2025-09-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0009_proof_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='condition',
            field=models.CharField(help_text="Description de la condition d'obtention", max_length=255),
        ),
        migrations.AlterField(
            model_name='badge',
            name='reward_value',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
    ]
