# Generated by Django 5.2.5 on 2025-09-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0011_product_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='commission_amount',
            field=models.DecimalField(decimal_places=7, default=0.0, help_text='Commission prise par la plateforme', max_digits=19),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payout_id',
            field=models.CharField(blank=True, help_text="ID du paiement de l'app vers le vendeur", max_length=255, null=True),
        ),
    ]
