# Generated by Django 5.2.5 on 2025-09-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0012_purchase_commission_amount_purchase_payout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tourisme', 'Tourisme'), ('artisanat', 'Artisanat'), ('services', 'Services'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
